import Head from "next/head";
import Link from "next/link";

import { useQuery } from "urql";
import { PRODUCT_QUERY } from "../lib/query";

export default function Home() {
  // FETCH FROM STRAPI WITH URQL AND GRAPHQL QUERY:
  const [results] = useQuery({ query: PRODUCT_QUERY });
  const { data, fetching, error } = results;
  if (fetching) return <p>Loading...</p>;
  if (error) return <p>Oh no! {error.message}</p>;
  console.log(data);
  return (
    <div>
      <Head>
        <title>Superdry</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Superdry+</h1>
        <Link href={"/about"} children="About" />
      </main>
    </div>
  );
}
